version: "3.9"

# ──────────────── Common env-file anchor ────────────────
x-env: &envfile
  env_file: .env

networks:
  airflow:
    driver: bridge

services:

  ###########################################################################
  # 1) Copilot – FastAPI + LangGraph agent (handles DB init internally)
  ###########################################################################
  copilot:
    image: thedatacarpenter/airflow-copilot:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: copilot
    restart: unless-stopped
    ports:
      - "3978:3978"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://<your url>:3978/health"]
      interval: 5s
      timeout: 60s
      retries: 5
    environment:
      USE_DOTENV: false

      # LLM / model
      LLM_MODEL_PROVIDER_NAME: ${LLM_MODEL_PROVIDER_NAME}
      LLM_MODEL_NAME: ${LLM_MODEL_NAME}

      # Provider keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_GENAI_API_KEY: ${GOOGLE_GENAI_API_KEY}
      # GROQ_API_KEY: ${GROQ_API_KEY}
      # ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

      # Summarization thresholds
      MIN_MSG_TO_SUMMARIZE: ${MIN_MSG_TO_SUMMARIZE:-10}
      MIN_MSG_TO_RETAIN: ${MIN_MSG_TO_RETAIN:-10}

      # Airflow connection
      AIRFLOW_AUTH_STRATEGY: ${AIRFLOW_AUTH_STRATEGY:-per_user}
      AIRFLOW_USER_NAME: ${AIRFLOW_USER_NAME:-airflow}
      AIRFLOW_USER_PASSWORD: ${AIRFLOW_USER_PASSWORD:-airflow}
      AIRFLOW_BASE_URL: ${AIRFLOW_BASE_URL}

      # Summarization model
      SUMMARIZATION_LLM_MODEL_PROVIDER_NAME: ${SUMMARIZATION_LLM_MODEL_PROVIDER_NAME}
      SUMMARIZATION_LLM_MODEL_NAME: ${SUMMARIZATION_LLM_MODEL_NAME}

      # Database & Bot
      DB_URI: ${DB_URI}
      MICROSOFT_APP_ID: ${MICROSOFT_APP_ID}
      MICROSOFT_APP_PASSWORD: ${MICROSOFT_APP_PASSWORD}

      # Encryption
      FERNET_SECRET_KEY: ${FERNET_SECRET_KEY}
    volumes:
      - .env:/app/src/.env:ro
    networks: [airflow]
